apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app2
  namespace: argocd
spec:
  destination:
    namespace: sucre
    server: https://kubernetes.default.svc
  project: project-1
  source:
    directory:
      recurse: true
    path: env/default
    targetRevision: main
    repoURL: https://github.com/sucre4me/argocd_demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
