apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-myapp
  labels:
    app: nginx
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ubuntu/nginx
        ports:
        - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: nginx
