apiVersion: apps/v1
kind: Deployment
metadata:
  name: madapi
  labels:
    app: madapi
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: madapi
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: madapi
